init:
- appveyor version
- ps: Update-AppveyorBuild -Message "Image '$env:APPVEYOR_BUILD_WORKER_IMAGE'@'$env:APPVEYOR_BUILD_WORKER_CLOUD' cloud. $env:APPVEYOR_REPO_COMMIT_MESSAGE"
- sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
- sh: echo $APPVEYOR_BUILD_WORKER_CLOUD
- sh: lsb_release -a

#install:
#- sh: sudo apt remove unattended-upgrades

test_script:
- sh: ls -al /etc/apt/apt.conf.d
- sh: ls -al /etc/cron.daily/
- sh: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 32EE5355A6BC6E42
- sh: sudo apt-get -y update
- sh: sudo apt-get -y upgrade

build: off

on_failure:
- sh: pgrep -a apt
- sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
