init:
- appveyor version
- ps: Update-AppveyorBuild -Message "Image '$env:APPVEYOR_BUILD_WORKER_IMAGE'@'$env:APPVEYOR_BUILD_WORKER_CLOUD' cloud. $env:APPVEYOR_REPO_COMMIT_MESSAGE"
- sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
- sh: echo $APPVEYOR_BUILD_WORKER_CLOUD
- sh: lsb_release -a

#install:
#- sh: sudo apt remove unattended-upgrades

test_script:
- sh: ls -al /etc/apt/apt.conf.d
- sh: sudo apt-get -y update
- sh: sudo apt-get -y upgrade

build: off

on_failure:
- sh: pgrep -a apt
